### ISSUE TITLE
Enable Supermicro deployments

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/JetSki#1]
Right now, at least the push button automation parts of JetSki are heavily geared towards Dell nodes and use badfish. Enabling deployments with Supermicro would mean substituting the badfish calls with equivalent ipmitool calls

**Comment by bengland2** [comment]
There is less that you can do with supermicros, AFAICT you can't change boot order without entering the BIOS.     However, we really need supermicro support because a large percentage of the scale lab consists of supermicros (because they were 1/2 price of Dell).   

It seems like the automation could tell whether it was dealing with a supermicro or not using the machine type embedded in the host name, for example.   But it's too bad that the ocp4_inventory.json file doesn't have machine type and other metadata embedded in it to make JetSki's job easier.   

Also, it always presents 4 NIC ports, but some systems have less than 4 NIC ports, or have different speeds on some of them.  It's hard to tell from the lab's ocp4_inventory.json what those interface names and types are.   For example, there are two different types of 1029u configurations with different interface names, but you can't tell which you are dealing with by looking at the hostname.   I had to install RHEL8 on all the 1029u machines in my reservation to figure out what sub-type they were.

**Comment by smalleni** [comment]
@bengland2  I think once https://github.com/redhat-performance/quads/issues/263 goes into QUADS it shoulde easy to expose that in the inventory file.

**Comment by bengland2** [comment]
sounds promising.  I'd like to have NIC interface metadata and storage device metadata.

**Comment by bengland2** [comment]
Sounds like there was some progress on this from e-mail stream, any updates?

**Comment by mrbojangles3** [comment]
`failed: [f09-h26-b01-5039ms.rdu2.scalelab.redhat.com] (item=f09-h26-b02-5039ms.rdu2.scalelab.redhat.com) => {"ansible_loop_var": "item", "attempts": 20, "changed": true, "cmd": "source /tmp/ansible.ptyl7iyc/.venv/bin/activate\n./src/badfis
h/badfish.py -u user -p password -i config/idrac_interfaces.yml -H mgmt-f09-h26-b02-5039ms.rdu2.scalelab.redhat.com --check-boot\n", "delta": "0:00:01.615184", "end": "2020-09-28 19:48:48.930993", "item": "f09-h26-b02-5039ms.rdu2.scalelab
.redhat.com", "msg": "non-zero return code", "rc": 1, "start": "2020-09-28 19:48:47.315809", "stderr": "- ERROR    - Could not retrieve Bios Boot mode.\n- ERROR    - There was something wrong executing Badfish.", "stderr_lines": ["- ERROR 
   - Could not retrieve Bios Boot mode.", "- ERROR    - There was something wrong executing Badfish."], "stdout": "", "stdout_lines": []}
`
Got this error when using supermicro 5039ms, sensitive info removed.

**Comment by smalleni** [comment]
@mrbojangles3 As we have discussed previously, you need to sub out badfish calls with ipmitool on supermicros afaik.

**Comment by mrbojangles3** [comment]
I was under the impression somehow that with the new idrac work that is vendor dependent jetski would gracefully "fail" to  ipmitool. got my wires crossed.

**Comment by grafuls** [comment]
There is no Redfish entrypoint for checking boot order on SuperMicros. 
What is the equivalent ipmitool instruction you would use and what is the output expected.
Would it help to have a more accurate error message from Badfish or is there any other output you would like to see there?
