### ISSUE TITLE
Error in TASK [bootstrap : detect python interpreter when Jetski is run in Alias lab

### ISSUE THREAD

**Issue by ashishkamra** [redhat-performance/JetSki#16]
Not sure why but may the RHEL 8.1 image in Alias does not have the /usr/bin/python symlink setup

```
TASK [bootstrap : detect python interpreter] *********************************************************************************
Wednesday 03 June 2020  14:45:57 -0400 (0:00:00.058)       0:16:34.470 ******** 
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ssh -o 'PreferredAuthentications=publickey' -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile /dev/null' root@e25-h13-740xd.alias.bos.scalelab.redhat.com /usr/bin/python --version\n", "delta": "0:00:00.247805", "end": "2020-06-03 14:45:57.839157", "msg": "non-zero return code", "rc": 127, "start": "2020-06-03 14:45:57.591352", "stderr": "Warning: Permanently added 'e25-h13-740xd.alias.bos.scalelab.redhat.com,10.19.96.124' (ECDSA) to the list of known hosts.\r\nbash: /usr/bin/python: No such file or directory", "stderr_lines": ["Warning: Permanently added 'e25-h13-740xd.alias.bos.scalelab.redhat.com,10.19.96.124' (ECDSA) to the list of known hosts.", "bash: /usr/bin/python: No such file or directory"], "stdout": "", "stdout_lines": []}
...ignoring
```

**Comment by smalleni** [comment]
That is fine, all this task is doing is checking for that file, so it knows what python interpreter to use when ansible connects. This is not killing your run afaik, is that right?

**Comment by smalleni** [comment]
Let me explain better,

The task of this file https://github.com/redhat-performance/JetSki/blob/master/ansible-ipi-install/roles/bootstrap/tasks/30_get_interpreter.yml is to figure out the python version on the host so that the appropriate ansible_python_interpreter can be set for ansible since ansible doesn'tdo a good job about setting the python_interpreter it needs to use when operating against a remote host.

What the code is doing is, it's checking for /usr/bin/python file and since it doesn't exist it defaults to using /usr/libexec/platform-python through the ternary condition. This is expected behavior, please let me know if I can close this issue.

**Comment by ashishkamra** [comment]
ok, sounds good.
