### ISSUE TITLE
public nics not disable on master nodes for > 4.7.45 for rdu lab

### ISSUE THREAD

**Issue by wilsondav** [redhat-performance/JetSki#208]
we need https://github.com/redhat-performance/JetSki/blob/master/ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2#L27-L33 to reflect 4.7 also as this appears in some later releases and we hit this bug.

https://bugzilla.redhat.com/show_bug.cgi?id=1984708

**Comment by dustinblack** [comment]
A relevant BZ comment seems to be here: https://bugzilla.redhat.com/show_bug.cgi?id=1982821#c3

> In 4.8, we added the "ip=dhcp" option to the kernel boot args in order to get consistent networking in dual stack environments.

But this references the change only for 4.8. I've asked for a link to the BZ where this change was implemented so that we can track down any apparent backports to 4.7.z. I'm not sure if changing https://github.com/redhat-performance/JetSki/blob/ab0bba1094226119fca1f7feb4bdc3b73d6c67e9/ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2#L27 to `>= 7` will work universally for 4.7 or only for a later build that perhaps has this apparent backport.

**Comment by dustinblack** [comment]
OK, here is the 4.7.z BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1973367

However, it is CLOSED CURRENTRELEASE but with the last comment noting that no 4.7.z backport was done.
