### ISSUE TITLE
Add async task to auto-approve CSRs

### ISSUE THREAD

**Issue by dustinblack** [redhat-performance/JetSki#24]
Because of network conditions that are specific to our lab infrastructure, the CSRs for workers deployed at install-time are not auto-approve. This means that unless a user manually approves the CSRs, and installation that includes workers will time out and the ansible task will fail (though if you approve the CSRs after this point, the OCP deployment will proceed to finish).

We should add an async task prior to starting the installer that looks for and approves CSRs in a loop until the installer task completes.

**Comment by smalleni** [comment]
Interesting that I don't run into this even when I don't disable any NICs per say.

**Comment by dustinblack** [comment]
Are you deploying workers? It won't happen in a masters-only deployment.

**Comment by smalleni** [comment]
I am, let me go back and see what I'm doing differently...

**Comment by smalleni** [comment]
My bad, I did have the NIC disabled. This change needs to go into the parent repository at https://github.com/openshift-kni/baremetal-deploy/blob/master/ansible-ipi-install/roles/installer/tasks/60_deploy_ocp.ymlso, so the PR has to be opened against https://github.com/openshift-kni/baremetal-deploy since we don't want to maintain separate changes in the node-prep and installer roles. I'm happy to work on this or let someone else who'd like to make a contribution pick this up.

**Comment by smalleni** [comment]
@jaredoconnell would you be interested in working on this? I can do a quick walkthrough of what is needed, if you have questions.

**Comment by jaredoconnell** [comment]
> @jaredoconnell would you be interested in working on this? I can do a quick walkthrough of what is needed, if you have questions.
> 
> @dustinblack FYI

Sure. I can work on this.
